// Backfill Event.extraFeeOptions - migrate_old_data.ts already parsed old's
// extra_fee_options JSON into an in-memory map (eventExtraOptions), but only
// ever used it to resolve BOOKINGS' own selectedExtras indices - it was
// never actually written back onto the Event record itself, so every
// migrated event's extraFeeOptions ended up permanently null (all 1306
// published events, confirmed) even though a booking on that same event
// could still reference a real historical selection by title (proving the
// old data genuinely existed).
//
// Usage:
//   node scripts/backfill_event_extra_fee_options_2026-09-27.js --dry-run
//   node scripts/backfill_event_extra_fee_options_2026-09-27.js            (applies + writes portable .sql)

require('dotenv/config');
const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');
const { PrismaClient, Prisma } = require('@prisma/client');
const { PrismaMariaDb } = require('@prisma/adapter-mariadb');

const DRY_RUN = process.argv.includes('--dry-run');

function stripEntities(s) {
  return (s || '').replace(/&#?\w+;/g, '').trim();
}

(async () => {
  const oldConn = await mysql.createConnection({ host: '127.0.0.1', user: 'root', password: '', database: 'd03dbe51', charset: 'utf8mb4' });
  const adapter = new PrismaMariaDb(process.env.DATABASE_URL);
  const prisma = new PrismaClient({ adapter });

  const events = await prisma.event.findMany({
    where: { eventNumber: { not: null }, extraFeeOptions: { equals: Prisma.DbNull } },
    select: { id: true, eventNumber: true }
  });
  console.log(`Events with eventNumber and currently-null extraFeeOptions: ${events.length}`);

  const eventNumbers = [...new Set(events.map(e => Number(e.eventNumber)))];
  const [oldRows] = await oldConn.query(
    `SELECT id, extra_fee_options FROM hiron_matukio WHERE id IN (${eventNumbers.join(',')}) AND extra_fee_options IS NOT NULL AND extra_fee_options != '' AND extra_fee_options != '[]'`
  );
  const optionsByOldId = new Map();
  for (const row of oldRows) {
    try {
      const parsed = JSON.parse(row.extra_fee_options);
      if (Array.isArray(parsed) && parsed.length) {
        optionsByOldId.set(row.id, parsed.map(o => ({
          title: stripEntities(o.title) || 'Option',
          value: parseFloat(o.value) || 0,
          perPlace: [true, 'true', 1, '1'].includes(o.perPlace),
        })));
      }
    } catch (e) { /* leave unset for this old event */ }
  }
  console.log(`Old events with real, parseable extra_fee_options: ${optionsByOldId.size}`);

  let updated = 0;
  const sqlLines = [
    '-- Backfill Event.extraFeeOptions (2026-09-27) - migrate_old_data.ts parsed',
    '-- this but never wrote it back onto the Event record itself.',
    '-- Generated by backfill_event_extra_fee_options_2026-09-27.js',
    '',
  ];

  for (const event of events) {
    const options = optionsByOldId.get(Number(event.eventNumber));
    if (!options) continue;
    updated++;
    if (!DRY_RUN) {
      await prisma.event.update({ where: { id: event.id }, data: { extraFeeOptions: options } });
      const json = JSON.stringify(options).replace(/\\/g, '\\\\').replace(/'/g, "''");
      sqlLines.push(`UPDATE Event SET extraFeeOptions = '${json}' WHERE id = '${event.id}'; -- eventNumber ${event.eventNumber}`);
    } else {
      console.log(`[dry-run] event ${event.id} (eventNumber ${event.eventNumber}): ${JSON.stringify(options)}`);
    }
  }

  console.log(`\nEvents ${DRY_RUN ? 'that would be updated' : 'updated'}: ${updated}`);

  if (!DRY_RUN) {
    const sqlPath = path.join(__dirname, 'backfill_event_extra_fee_options_2026-09-27.sql');
    fs.writeFileSync(sqlPath, sqlLines.join('\n') + '\n');
    console.log(`Portable SQL written to ${sqlPath}`);
  }

  await oldConn.end();
  await prisma.$disconnect();
})();
