// One-time backfill: the existing "default" TemplatesConfig row was created
// at some earlier point with listViews/certificates/csvXml left as SQL
// NULL and invoices/tickets as empty {} - the GET route's own
// create-if-missing defaults (now populated with old Matukio's real,
// word-for-word content) never got a chance to run since a row already
// existed. This applies that same real content directly via UPDATE.
//
// Usage: node scripts/backfill_templates_config_2026-09-27.js

require('dotenv/config');
const { PrismaClient } = require('@prisma/client');
const { PrismaMariaDb } = require('@prisma/adapter-mariadb');

const adapter = new PrismaMariaDb(process.env.DATABASE_URL);
const prisma = new PrismaClient({ adapter });

const listViews = {
  signatureList: 'Unterschriftsliste\n\nNr.: MAT_EVENT_NUMBER\nVeranstaltung: MAT_EVENT_TITLE\nBeginn: MAT_EVENT_BEGIN\nEnde: MAT_EVENT_END\nGebühren: MAT_EVENT_FEES\n\nMAT_NR MAT_BOOKING_NUMBER MAT_BOOKING_FIRSTNAME MAT_BOOKING_LASTNAME MAT_SIGN',
  participantList: 'Teilnehmerliste\n\nNr.: MAT_EVENT_NUMBER\nAnrede: MAT_EVENT_TITLE\nBeginn: MAT_EVENT_BEGIN\nEnde: MAT_EVENT_END\nGebühren: MAT_EVENT_FEES\n\nName: MAT_BOOKING_NAME\nE-Mail: MAT_BOOKING_EMAIL\nBuchungsnummer: MAT_BOOKING_NUMBER\nStatus: MAT_BOOKING_STATUS\nGebuchte Plätze: MAT_BOOKING_BOOKEDNR\nGebühren: MAT_BOOKING_FEES_STATUS\nMAT_BOOKING_QRCODE_ID',
};

const invoices = {
  pdfTemplate: '<table width="100%"><tr><td>Your Company<br>Your Company Address<br>Your Tax Number</td><td align="right">Your Logo</td></tr></table><br><br><table width="100%"><tr><td><b>Customer Information</b><br>MAT_BOOKING_NAME<br>MAT_BOOKING_STREET<br>MAT_BOOKING_ZIP MAT_BOOKING_CITY<br>MAT_BOOKING_COUNTRY</td><td><b>Invoice Information</b><br>Invoice Number: MAT_INVOICE_NUMBER<br>Invoice Date: MAT_INVOICE_DATE<br>Booking Number: MAT_BOOKING_NUMBER<br>Payment method: MAT_BOOKING_PAYMENT_METHOD</td></tr></table><br><br><table width="100%" border="1"><tr><th>#</th><th>Event</th><th>Net total</th></tr><tr><td>MAT_BOOKING_NRBOOKED</td><td>MAT_EVENT_TITLE</td><td>MAT_BOOKING_PAYMENT_NETTO</td></tr></table><br><div align="right">Net total: MAT_BOOKING_PAYMENT_NETTO<br>Tax total: MAT_BOOKING_PAYMENT_TAX<br><b>Total: MAT_BOOKING_PAYMENT_BRUTTO</b></div><br><br><b>Invoice Note</b><br>Your notes',
  emailSubject: 'Ihre Rechnung MAT_BOOKING_NUMBER',
  emailBody: '<div id="mat-invoice-mail"><p><span style="line-height: 1.3em;">Sehr geehrte / geehrter MAT_BOOKING_NAME,<br /><br /></span>im Anhang finden Sie die Rechnung zu Ihrer Buchung.</p><p>MAT_SIGNATURE</p></div>',
};

const certificates = {
  pdfTemplate: '<h2>Zertifikat erteilen for</h2><h3>MAT_BOOKING_NAME</h3><h4>hat erfolgreich an der Veranstaltung teilgenommen</h4><h4>MAT_EVENT_TITLE</h4><h4>Datum: MAT_DATE</h4>',
  backgroundImage: '',
  emailSubject: 'Your certificate for MAT_EVENT_TITLE MAT_EVENT_SEMNUM',
  emailBody: 'Sehr geehrte / geehrter MAT_BOOKING_NAME,<br /><br />Sie wurden für die unten stehende Veranstaltung zertifiziert. <br /><br />Sie wurden für die unten stehende Veranstaltung zertifiziert. MAT_EVENT_ALL_DETAILS_HTML MAT_SIGNATURE',
};

const tickets = {
  ticketTemplate: 'MAT_EVENT_TITLE - MAT_EVENT_BEGIN\nMAT_BOOKING_NRBOOKED\nMAT_BOOKING_NUMBER\nMAT_BOOKING_CHECKIN_QRCODE\nMAT_BOOKING_PAYMENT_BRUTTO',
  backgroundImage: '',
  nametagTemplate: 'MAT_BOOKING_FIRSTNAME MAT_BOOKING_LASTNAME\nMAT_BOOKING_COUNTRY\n\nMAT_EVENT_TITLE &nbsp; MAT_BOOKING_ID',
  nametagBackgroundImage: 'images/powered_by.png',
};

const csvXml = {
  csvTemplate: "'MAT_BOOKING_NUMBER';'MAT_EVENT_TITLE';'MAT_CSV_BOOKING_DETAILS';'MAT_BOOKING_PAYMENT_BRUTTO';'MAT_BOOKING_NAME';'MAT_BOOKING_PAYMENT_METHOD';'MAT_BOOKING_STATUS';'MAT_BOOKING_EXTRA_PAYMENT_OPTIONS';'MAT_BOOKING_PAYMENT_STATUS';'",
  xmlTemplate: '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<!-- Generated by Matukio -->\n<BOOKING>\n<BOOKING_NUMBER>MAT_BOOKING_NUMBER</BOOKING_NUMBER>\n<EVENT>MAT_EVENT_TITLE</EVENT>\n<EVENT_NUMBER>MAT_EVENT_NUMBER</EVENT_NUMBER>\n<TITLE>MAT_BOOKING_TITLE</TITLE>\n<FIRSTNAME>MAT_BOOKING_FIRSTNAME</FIRSTNAME>\n<LASTNAME>MAT_BOOKING_LASTNAME</LASTNAME>\n<COMPANY>MAT_BOOKING_COMPANY</COMPANY>\n<STREET>MAT_BOOKING_STREET</STREET>\n<ZIPCODE>MAT_BOOKING_ZIP</ZIPCODE>\n<CITY>MAT_BOOKING_CITY</CITY>\n<COUNTRY>MAT_BOOKING_COUNTRY</COUNTRY>\n<PHONE>MAT_BOOKING_PHONE</PHONE>\n<MOBILE>MAT_BOOKING_MOBILE</MOBILE>\n<EMAIL>MAT_BOOKING_EMAIL</EMAIL>\n<COMMENT>MAT_BOOKING_COMMENT</COMMENT>\n<PLACES>MAT_BOOKING_BOOKEDNR</PLACES>\n<AMOUNT>MAT_BOOKING_GROSS</AMOUNT>\n<PERSONS>\nMAT_XML_BOOKING_OTHER_PERSON_DATA\n</PERSONS>\n</BOOKING>',
};

(async () => {
  const existing = await prisma.templatesConfig.findUnique({ where: { id: 'default' } });
  if (!existing) {
    console.log('No existing "default" row - nothing to backfill (GET route will create it fresh with the real content already).');
    await prisma.$disconnect();
    return;
  }

  console.log('Before:', JSON.stringify({
    listViews: existing.listViews,
    invoices: existing.invoices,
    certificates: existing.certificates,
    tickets: existing.tickets,
    csvXml: existing.csvXml,
  }));

  await prisma.templatesConfig.update({
    where: { id: 'default' },
    data: { listViews, invoices, certificates, tickets, csvXml },
  });

  console.log('Backfilled listViews/invoices/certificates/tickets/csvXml on the "default" TemplatesConfig row.');
  await prisma.$disconnect();
})();
