// Backfill: 6926 of 7301 migrated bookings have paymentMethod = NULL even
// though migrate_old_data.ts's current code does set it - these rows were
// created by an older run of the script (before that field existed in the
// create() call) and a re-run only creates missing bookings, never updates
// existing ones, so they were stuck without it.
//
// Label mapping taken from the site's own actual Joomla payment-plugin
// configuration (hiron_extensions.params.plugin_name), which is what old's
// getPaymentMethodTitle() really displays - not a generic guess. Notably
// the "cash" plugin's display name was site-customized to "Gutschein", not
// "Barzahlung".
//
// Usage:
//   node scripts/backfill_booking_payment_method_2026-09-20.js --dry-run
//   node scripts/backfill_booking_payment_method_2026-09-20.js

require('dotenv/config');
const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');
const { PrismaClient } = require('@prisma/client');
const { PrismaMariaDb } = require('@prisma/adapter-mariadb');

const DRY_RUN = process.argv.includes('--dry-run');

const PAYMENT_METHOD_LABEL = {
  cash: 'Gutschein',
  payment_cash: 'Gutschein',
  banktransfer: 'Überweisung',
  payment_banktransfer: 'Überweisung',
  postfinance: 'Postfinance',
  girocheckout: 'girocheckout',
};

(async () => {
  const oldConn = await mysql.createConnection({ host: '127.0.0.1', user: 'root', password: '', database: 'd03dbe51', charset: 'utf8mb4' });
  const adapter = new PrismaMariaDb(process.env.DATABASE_URL);
  const prisma = new PrismaClient({ adapter });

  const allBookings = await prisma.booking.findMany();
  const bookings = allBookings.filter(
    (b) => (b.customerDetails)?.source === 'migrated_from_matukio' && !b.paymentMethod
  );
  console.log(`Migrated bookings with missing paymentMethod: ${bookings.length}`);

  const oldIds = bookings.map((b) => (b.customerDetails).oldBookingId).filter(Boolean);
  const [oldRows] = await oldConn.query(
    `SELECT id, payment_method FROM hiron_matukio_bookings WHERE id IN (${oldIds.join(',')})`
  );
  const oldById = new Map(oldRows.map((r) => [r.id, r]));

  let updated = 0;
  let skipped = 0;
  const sqlLines = [
    '-- Backfill Booking.paymentMethod from old payment_method (2026-09-20)',
    '-- Generated by backfill_booking_payment_method_2026-09-20.js',
    ''
  ];

  for (const booking of bookings) {
    const oldBookingId = (booking.customerDetails).oldBookingId;
    const oldRow = oldById.get(oldBookingId);
    const rawMethod = oldRow?.payment_method?.trim();
    if (!rawMethod) { skipped++; continue; }

    const label = PAYMENT_METHOD_LABEL[rawMethod] || rawMethod;
    updated++;

    if (!DRY_RUN) {
      await prisma.booking.update({ where: { id: booking.id }, data: { paymentMethod: label } });
      sqlLines.push(`UPDATE Booking SET paymentMethod = '${label.replace(/'/g, "''")}' WHERE id = '${booking.id}'; -- old booking ${oldBookingId} (raw: ${rawMethod})`);
    }
  }

  console.log(`Bookings updated: ${updated}`);
  console.log(`Skipped (no payment_method on old row): ${skipped}`);

  if (!DRY_RUN) {
    const sqlPath = path.join(__dirname, 'backfill_booking_payment_method_2026-09-20.sql');
    fs.writeFileSync(sqlPath, sqlLines.join('\n') + '\n');
    console.log(`SQL file written to ${sqlPath}`);
  }

  await oldConn.end();
  await prisma.$disconnect();
})();
