// Backfill EventTicket.order (new column, all default to 0 today) so the
// booking form lists ticket types in old Matukio's own order: "Normal"
// (the base fee) first, then each different_fees_override entry in the
// exact order the admin originally entered them - matching feetype.php's
// own <option> build order exactly, instead of whatever arbitrary order a
// random-UUID-keyed row happened to come back in.
//
// For a migrated event (has eventNumber), the correct order is reconstructed
// from the OLD DB's different_fees_override JSON array position. For a
// non-migrated (admin-created) event, there's no old source of truth - this
// just guarantees any ticket literally named "Normal" sorts first, and
// leaves the rest in whatever order they're currently returned in.
//
// Usage:
//   node scripts/backfill_ticket_order_2026-09-27.js --dry-run
//   node scripts/backfill_ticket_order_2026-09-27.js            (applies + writes portable .sql)

require('dotenv/config');
const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');
const { PrismaClient } = require('@prisma/client');
const { PrismaMariaDb } = require('@prisma/adapter-mariadb');

const DRY_RUN = process.argv.includes('--dry-run');

(async () => {
  const oldConn = await mysql.createConnection({ host: '127.0.0.1', user: 'root', password: '', database: 'd03dbe51', charset: 'utf8mb4' });
  const adapter = new PrismaMariaDb(process.env.DATABASE_URL);
  const prisma = new PrismaClient({ adapter });

  const events = await prisma.event.findMany({ include: { tickets: true } });

  let updated = 0;
  const sqlLines = [
    '-- Backfill EventTicket.order (2026-09-27) - "Normal" first, then old\'s',
    '-- different_fees_override array order, matching old Matukio exactly.',
    '-- Generated by backfill_ticket_order_2026-09-27.js',
    '',
  ];

  for (const event of events) {
    if (event.tickets.length < 2) continue; // nothing to order

    let orderByName = new Map(); // name -> order

    if (event.eventNumber) {
      const [rows] = await oldConn.query(
        'SELECT different_fees_override FROM hiron_matukio WHERE id = ?',
        [Number(event.eventNumber)]
      );
      const oldRow = rows[0];
      if (oldRow && oldRow.different_fees_override) {
        try {
          const overrides = JSON.parse(oldRow.different_fees_override);
          if (Array.isArray(overrides)) {
            orderByName.set('Normal', 0);
            overrides.forEach((o, i) => {
              const title = (o.title || `Option ${o.id}`).replace(/<[^>]*>/g, '').trim();
              if (!orderByName.has(title)) orderByName.set(title, i + 1);
            });
          }
        } catch (e) { /* fall through to name-only heuristic below */ }
      }
    }

    // Name-only fallback (non-migrated event, or old row/override missing):
    // guarantee "Normal" is first, keep everything else in its current
    // relative order.
    if (orderByName.size === 0) {
      let next = 1;
      for (const t of event.tickets) {
        if (t.name === 'Normal') { orderByName.set(t.name, 0); continue; }
        if (!orderByName.has(t.name)) orderByName.set(t.name, next++);
      }
    }

    for (const ticket of event.tickets) {
      const newOrder = orderByName.has(ticket.name) ? orderByName.get(ticket.name) : 999;
      if (ticket.order === newOrder) continue;
      updated++;
      if (!DRY_RUN) {
        await prisma.eventTicket.update({ where: { id: ticket.id }, data: { order: newOrder } });
        sqlLines.push(`UPDATE EventTicket SET \`order\` = ${newOrder} WHERE id = '${ticket.id}'; -- event ${event.id} (${event.eventNumber || 'no eventNumber'}) ticket "${ticket.name.replace(/'/g, "''")}"`);
      } else {
        console.log(`[dry-run] event ${event.id} (${event.eventNumber || 'no eventNumber'}) ticket "${ticket.name}": ${ticket.order} -> ${newOrder}`);
      }
    }
  }

  console.log(`\nTickets ${DRY_RUN ? 'that would be updated' : 'updated'}: ${updated}`);

  if (!DRY_RUN) {
    const sqlPath = path.join(__dirname, 'backfill_ticket_order_2026-09-27.sql');
    fs.writeFileSync(sqlPath, sqlLines.join('\n') + '\n');
    console.log(`Portable SQL written to ${sqlPath}`);
  }

  await oldConn.end();
  await prisma.$disconnect();
})();
