// Backfill: 1276 migrated bookings had a real old.extra_fees selection
// (indices into the event's extra_fee_options array) that migrate_old_data.ts
// never carried over at all. The live booking flow (EventBookingModal.tsx)
// stores this as customerDetails.selectedExtras = [{title,value,perPlace}],
// which is also what the new CSV export's "Zusätzliche Optionen" column
// reads - without this backfill that column would silently show "no
// options booked" for every one of these 1276 real historical selections.
//
// Usage:
//   node scripts/backfill_booking_selected_extras_2026-09-20.js --dry-run
//   node scripts/backfill_booking_selected_extras_2026-09-20.js

require('dotenv/config');
const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');
const { PrismaClient } = require('@prisma/client');
const { PrismaMariaDb } = require('@prisma/adapter-mariadb');

const DRY_RUN = process.argv.includes('--dry-run');

(async () => {
  const oldConn = await mysql.createConnection({ host: '127.0.0.1', user: 'root', password: '', database: 'd03dbe51', charset: 'utf8mb4' });
  const adapter = new PrismaMariaDb(process.env.DATABASE_URL);
  const prisma = new PrismaClient({ adapter });

  const allBookings = await prisma.booking.findMany();
  const bookings = allBookings.filter(b => (b.customerDetails)?.source === 'migrated_from_matukio');

  const oldIds = bookings.map(b => (b.customerDetails).oldBookingId).filter(Boolean);
  const [oldRows] = await oldConn.query(
    `SELECT id, semid, extra_fees FROM hiron_matukio_bookings WHERE id IN (${oldIds.join(',')}) AND extra_fees IS NOT NULL AND extra_fees != '' AND extra_fees != '[]'`
  );
  console.log(`Old bookings with real extra_fees: ${oldRows.length}`);

  const semids = [...new Set(oldRows.map(r => r.semid))];
  const [recurringRows] = await oldConn.query(
    `SELECT id, event_id FROM hiron_matukio_recurring WHERE id IN (${semids.join(',')})`
  );
  const semidToEventId = new Map(recurringRows.map(r => [r.id, r.event_id]));

  const eventIds = [...new Set(recurringRows.map(r => r.event_id))];
  const [eventRows] = await oldConn.query(
    `SELECT id, extra_fee_options FROM hiron_matukio WHERE id IN (${eventIds.join(',')})`
  );
  const eventOptionsById = new Map();
  for (const row of eventRows) {
    if (!row.extra_fee_options) continue;
    try { eventOptionsById.set(row.id, JSON.parse(row.extra_fee_options)); } catch (e) { /* leave unset */ }
  }

  const oldBookingById = new Map(oldRows.map(r => [r.id, r]));
  const bookingByOldId = new Map(bookings.map(b => [(b.customerDetails).oldBookingId, b]));

  let updated = 0;
  let skippedNoMatch = 0;
  const sqlLines = [
    '-- Backfill Booking.customerDetails.selectedExtras from old extra_fees (2026-09-20)',
    '-- Generated by backfill_booking_selected_extras_2026-09-20.js',
    ''
  ];

  for (const [oldId, oldRow] of oldBookingById) {
    const booking = bookingByOldId.get(oldId);
    if (!booking) continue;

    let indices;
    try { indices = JSON.parse(oldRow.extra_fees); } catch (e) { skippedNoMatch++; continue; }
    if (!Array.isArray(indices) || indices.length === 0) continue;

    const eventId = semidToEventId.get(oldRow.semid);
    const options = eventOptionsById.get(eventId);
    if (!options) { skippedNoMatch++; continue; }

    const selectedExtras = indices
      .map(nr => options[Number(nr)])
      .filter(Boolean)
      .map(o => ({ title: o.title, value: parseFloat(o.value) || 0, perPlace: !!o.perPlace }));

    if (selectedExtras.length === 0) { skippedNoMatch++; continue; }

    updated++;
    const mergedDetails = { ...booking.customerDetails, selectedExtras };

    if (!DRY_RUN) {
      await prisma.booking.update({ where: { id: booking.id }, data: { customerDetails: mergedDetails } });
      sqlLines.push(`UPDATE Booking SET customerDetails = '${JSON.stringify(mergedDetails).replace(/'/g, "''")}' WHERE id = '${booking.id}'; -- old booking ${oldId}`);
    }
  }

  console.log(`Bookings updated: ${updated}`);
  console.log(`Skipped (no resolvable option data): ${skippedNoMatch}`);

  if (!DRY_RUN) {
    const sqlPath = path.join(__dirname, 'backfill_booking_selected_extras_2026-09-20.sql');
    fs.writeFileSync(sqlPath, sqlLines.join('\n') + '\n');
    console.log(`SQL file written to ${sqlPath}`);
  }

  await oldConn.end();
  await prisma.$disconnect();
})();
