// Backfill: bookings migrated from old Matukio (customerDetails.source ===
// 'migrated_from_matukio') never got the customer's registration-form
// answers - migrate_old_data.ts only ever copied name/email/language/
// paid/checkedIn into customerDetails. The real data (salutation, full
// name, birth date, size/weight, phone, street, zip, city, remarks) lives
// in hiron_matukio_bookings.newfields, a JSON blob keyed by the booking
// form's numeric field id - never read by the migration at all.
//
// Field-id -> meaning, taken directly from hiron_matukio_bookingform_field
// (the CURRENT, still-live booking form config; ids not present there are
// orphaned leftovers from an older form revision and are correctly
// ignored, since old's own live CSV export - driven by the same current
// field list - ignores them too):
//   2  -> salutation (Anrede)
//   4  -> fullName   (Vorname Nachname)
//   7  -> street
//   8  -> zip
//   9  -> city
//   12 -> email (already covered by customerDetails.email, cross-checked not overwritten if it disagrees)
//   13 -> phone
//   16 -> remarks (Bemerkung / Gutscheincode) - note: the OLD `comment`
//        column that migrate_old_data.ts actually read is empty for
//        essentially every booking; the real remarks text was always in
//        this newfields key instead, so Booking.remarks needs the same fix.
//   17 -> sizeWeight (Gewicht in kg - in practice free text, often
//        "height / weight" combined, matching our own live booking form's
//        equally free-text sizeWeight field)
//   18 -> birthDate
//
// Usage:
//   node scripts/backfill_booking_customer_details_2026-09-20.js --dry-run
//   node scripts/backfill_booking_customer_details_2026-09-20.js

require('dotenv/config');
const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');
const { PrismaClient } = require('@prisma/client');
const { PrismaMariaDb } = require('@prisma/adapter-mariadb');

const DRY_RUN = process.argv.includes('--dry-run');

const FIELD_MAP = {
  2: 'salutation',
  4: 'fullName',
  7: 'street',
  8: 'zip',
  9: 'city',
  13: 'phone',
  17: 'sizeWeight',
  18: 'birthDate',
};

function cleanText(s) {
  if (s === null || s === undefined) return null;
  const t = String(s).trim();
  return t.length ? t : null;
}

(async () => {
  const oldConn = await mysql.createConnection({ host: '127.0.0.1', user: 'root', password: '', database: 'd03dbe51', charset: 'utf8mb4' });
  const adapter = new PrismaMariaDb(process.env.DATABASE_URL);
  const prisma = new PrismaClient({ adapter });

  const allBookings = await prisma.booking.findMany();
  const bookings = allBookings.filter(b => (b.customerDetails)?.source === 'migrated_from_matukio');
  console.log(`Migrated bookings found: ${bookings.length}`);

  const oldIds = bookings.map(b => (b.customerDetails).oldBookingId).filter(Boolean);
  const [oldRows] = await oldConn.query(
    `SELECT id, newfields FROM hiron_matukio_bookings WHERE id IN (${oldIds.join(',')})`
  );
  const oldById = new Map(oldRows.map(r => [r.id, r]));

  let updated = 0;
  let noNewfields = 0;
  let remarksFixed = 0;
  const sqlLines = [
    '-- Backfill Booking.customerDetails + Booking.remarks from old newfields (2026-09-20)',
    '-- Generated by backfill_booking_customer_details_2026-09-20.js',
    ''
  ];

  for (const booking of bookings) {
    const oldBookingId = (booking.customerDetails).oldBookingId;
    const oldRow = oldById.get(oldBookingId);
    if (!oldRow || !oldRow.newfields) { noNewfields++; continue; }

    let parsed;
    try { parsed = JSON.parse(oldRow.newfields); } catch (e) { noNewfields++; continue; }

    const additions = {};
    for (const [fieldId, key] of Object.entries(FIELD_MAP)) {
      const val = cleanText(parsed[fieldId]);
      if (val !== null) additions[key] = val;
    }

    const newRemarks = additions.remarks;
    delete additions.remarks; // not a customerDetails key, goes on Booking.remarks directly
    const remarksFromNewfields = cleanText(parsed[16]);

    if (Object.keys(additions).length === 0 && !remarksFromNewfields) { noNewfields++; continue; }

    const mergedDetails = { ...(booking.customerDetails), ...additions };
    const remarksChanged = remarksFromNewfields && remarksFromNewfields !== booking.remarks;

    updated++;
    if (remarksChanged) remarksFixed++;

    if (!DRY_RUN) {
      await prisma.booking.update({
        where: { id: booking.id },
        data: {
          customerDetails: mergedDetails,
          ...(remarksChanged ? { remarks: remarksFromNewfields } : {}),
        },
      });
    }

    if (!DRY_RUN) {
      sqlLines.push(
        `UPDATE Booking SET customerDetails = '${JSON.stringify(mergedDetails).replace(/'/g, "''")}'` +
        (remarksChanged ? `, remarks = '${remarksFromNewfields.replace(/'/g, "''")}'` : '') +
        ` WHERE id = '${booking.id}'; -- old booking ${oldBookingId}`
      );
    }
  }

  console.log(`Bookings updated: ${updated}`);
  console.log(`Bookings with no usable newfields (left untouched): ${noNewfields}`);
  console.log(`Bookings where remarks was also corrected: ${remarksFixed}`);

  if (!DRY_RUN) {
    const sqlPath = path.join(__dirname, 'backfill_booking_customer_details_2026-09-20.sql');
    fs.writeFileSync(sqlPath, sqlLines.join('\n') + '\n');
    console.log(`SQL file written to ${sqlPath}`);
  }

  await oldConn.end();
  await prisma.$disconnect();
})();
