// Fix: TemplatesConfig.emails.bookingConfirmation.bodyHtml was generic
// placeholder text ("vielen Dank für Ihre Buchung bei der Flugschule
// Hirondelle...") - every real customer booking confirmation was silently
// missing old Matukio's actual, live business content
// (hiron_matukio_templates.tmpl_name='mail_booking'): the 4-week payment
// deadline policy, the real waitlist policy, the school's real bank
// details (IBAN/BIC), and the insurance recommendation with a real link.
// Found during a full admin-module audit (Templates section), not a
// design choice - this is customer-facing content that was actually being
// sent wrong.
//
// This only changes the *body copy*; the existing {BOOKING_NAME}/
// {EVENT_DETAILS}/{BOOKING_DETAILS} token system (backend/src/services/
// mailer.service.ts) is untouched. Idempotent - re-running just sets the
// same content again.
//
// Usage:
//   node scripts/fix_booking_confirmation_email_content_2026-09-20.js

require('dotenv/config');
const fs = require('fs');
const path = require('path');
const { PrismaClient } = require('@prisma/client');
const { PrismaMariaDb } = require('@prisma/adapter-mariadb');

const NEW_BODY_HTML = `
          <h3>Hallo {BOOKING_NAME},</h3>
          <p>vielen Dank für Ihre Buchung.</p>
          <br/>
          {EVENT_DETAILS}
          <br/>
          {BOOKING_DETAILS}
          <br/>
          <p>Im Anhang finden Sie Ihre Rechnung und Ihr Ticket.</p>
          <hr/>
          <p>Die Kursgebühr wird 4 Wochen vor Kursbeginn fällig. Bei Kurzfristbuchungen (ab vier Wochen vor Kursbeginn) wird der gesamte Kurspreis sofort fällig.</p>
          <p>Wir führen eine echte Warteliste (der Kurs ist dann tatsächlich ausgebucht). Buchungen auf Warteliste sind daher erst zu bezahlen, wenn die Teilnahme auch sicher - und der Platz verbindlich bestätigt ist.</p>
          <p><strong>Bankverbindung</strong><br/>
          Kontoinhaber: Alexander Schlink<br/>
          Sparkasse Südpfalz<br/>
          IBAN: DE32 5485 0010 1700 1976 41<br/>
          BIC: SOLADES1SUW</p>
          <hr/>
          <p style="color: #ff0000;">Wir empfehlen zur Absicherung für Stornos / Absagen den Abschluss einer Seminarversicherung bzw. für unsere mehrtätigen Kurse / Reisen zusätzlich eine Reiseversicherung. Infos dazu findet ihr auf unserer Seite <a href="https://www.fs-hirondelle.de/infos/versicherungen" style="color: #ff0000;">https://www.fs-hirondelle.de/infos/versicherungen</a>.</p>
          <hr/>
          <p>Mit freundlichen Grüßen,<br/>Ihr Team der Flugschule Hirondelle</p>
        `;

(async () => {
  const adapter = new PrismaMariaDb(process.env.DATABASE_URL);
  const prisma = new PrismaClient({ adapter });

  const config = await prisma.templatesConfig.findUnique({ where: { id: 'default' } });
  if (!config) {
    console.error('No TemplatesConfig row with id="default" found - nothing to update.');
    await prisma.$disconnect();
    return;
  }

  const emails = { ...config.emails };
  emails.bookingConfirmation = { ...emails.bookingConfirmation, bodyHtml: NEW_BODY_HTML };

  await prisma.templatesConfig.update({ where: { id: 'default' }, data: { emails } });
  console.log('Updated TemplatesConfig.emails.bookingConfirmation.bodyHtml with real content.');

  const sqlPath = path.join(__dirname, 'fix_booking_confirmation_email_content_2026-09-20.sql');
  fs.writeFileSync(
    sqlPath,
    `-- Fix booking confirmation email content (2026-09-20)\n` +
    `-- Generated by fix_booking_confirmation_email_content_2026-09-20.js\n` +
    `UPDATE TemplatesConfig SET emails = '${JSON.stringify(emails).replace(/'/g, "''")}' WHERE id = 'default';\n`
  );
  console.log(`SQL file written to ${sqlPath}`);

  await prisma.$disconnect();
})();
