// Backfill: old's hiron_acymailing_template has 6 rows, but only 2 are
// real site content (not AcyMailing's stock library) - tempid 4
// "Newsletter Allgemein" and tempid 12 "Newsletter Tandemflüge", both with
// real from-name/from-email set to the business, confirmed byte-for-byte
// matching a real migrated NewsletterCampaign body (same header bar color,
// same banner image path). These were never imported into NewsletterTemplate
// - an admin picking a template for a NEW campaign got only 2 unrelated,
// independently-designed templates, visually nothing like what the 677
// historical newsletters actually looked like.
//
// Safe to re-run: skips a tempid if a NewsletterTemplate with the same
// name already exists.
//
// Usage:
//   node scripts/migrate_acymailing_templates_2026-09-23.js --dry-run
//   node scripts/migrate_acymailing_templates_2026-09-23.js

require('dotenv/config');
const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');
const { PrismaClient } = require('@prisma/client');
const { PrismaMariaDb } = require('@prisma/adapter-mariadb');

const DRY_RUN = process.argv.includes('--dry-run');
const REAL_TEMPLATE_IDS = [4, 12];

function sqlEscape(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
}

async function main() {
  const oldConn = await mysql.createConnection({ host: '127.0.0.1', user: 'root', password: '', database: 'd03dbe51', charset: 'utf8mb4' });
  const adapter = new PrismaMariaDb(process.env.DATABASE_URL);
  const prisma = new PrismaClient({ adapter });

  const [rows] = await oldConn.query(
    `SELECT tempid, name, body FROM hiron_acymailing_template WHERE tempid IN (${REAL_TEMPLATE_IDS.join(',')})`
  );

  console.log(`Real templates found in old DB: ${rows.length}`);

  let created = 0;
  let skippedExisting = 0;
  const sqlLines = [
    '-- Backfill NewsletterTemplate from old AcyMailing real templates (2026-09-23)',
    '-- Generated by migrate_acymailing_templates_2026-09-23.js',
    ''
  ];

  for (const row of rows) {
    const existing = await prisma.newsletterTemplate.findFirst({ where: { name: row.name } });
    if (existing) { skippedExisting++; continue; }

    created++;
    if (!DRY_RUN) {
      const created_row = await prisma.newsletterTemplate.create({
        data: { name: row.name, body: row.body || '', design: null }
      });
      sqlLines.push(
        `INSERT INTO NewsletterTemplate (id, name, body, design, thumbnailUrl, createdAt, updatedAt) VALUES (` +
        [sqlEscape(created_row.id), sqlEscape(row.name), sqlEscape(row.body || ''), 'NULL', 'NULL', sqlEscape(created_row.createdAt.toISOString().slice(0, 19).replace('T', ' ')), sqlEscape(created_row.updatedAt.toISOString().slice(0, 19).replace('T', ' '))].join(', ') +
        `); -- old tempid ${row.tempid}`
      );
    }
  }

  console.log(`Templates created: ${created}`);
  console.log(`Skipped (already migrated, same name): ${skippedExisting}`);

  if (!DRY_RUN) {
    const sqlPath = path.join(__dirname, 'migrate_acymailing_templates_2026-09-23.sql');
    fs.writeFileSync(sqlPath, sqlLines.join('\n') + '\n', { encoding: 'utf8' });
    console.log(`SQL file written to ${sqlPath}`);
  }

  await oldConn.end();
  await prisma.$disconnect();
}

main().catch((err) => {
  console.error('Migration failed:', err);
  process.exit(1);
});
