-- Backfill NewsletterTemplate from old AcyMailing real templates (2026-09-23)
-- Generated by migrate_acymailing_templates_2026-09-23.js

INSERT INTO NewsletterTemplate (id, name, body, design, thumbnailUrl, createdAt, updatedAt) VALUES ('95f321ce-2cfd-4adc-8369-1516fec8f0cd', 'Newsletter Allgemein', '<div style="text-align: center; width: 100%; background-color: #fff;">
<table style="text-align: justify; margin: auto; background-color: #ebebeb; border: 1px solid #e7e7e7; width: 600px;" cellspacing="0" cellpadding="0" align="center" bgcolor="#ebebeb">
<tbody class="acyeditor_sortable">
<tr style="line-height: 0px;">
<td style="background-color: #69b4c0; height: 38px;" valign="bottom"><img src="media/com_acymailing/templates/newsletter-4/top.png" alt=" - - - " width="600" height="38" /></td>
</tr>
<tr>
<td style="text-align: center; width: 600px;">
<table border="0" style="margin: auto; width: 600px;" cellspacing="0" cellpadding="0">
<tbody class="acyeditor_sortable">
<tr class="acyeditor_delete">
<td style="background-color: #ebebeb; width: 40px;">&nbsp;</td>
<td class="acyeditor_text" style="padding: 20px 0px; text-align: left; background-color: #ebebeb; width: 520px;"><img src="media/com_acymailing/templates/newsletter-4/message_icon.png" alt="-" width="41" height="41" style="margin: 0px 10px; float: left;" />
<h3><span style="color: #3491b7;">NEWSLETTER</span></h3>
</td>
</tr>
</tbody>
<tbody class="acyeditor_sortable">
<tr>
<td style="background-color: #ebebeb; width: 40px;">&nbsp;</td>
<td class="acyeditor_text" style="padding: 20px 0px; text-align: left; background-color: #fefefe; width: 520px;"><a href="http://www.flugschule-hirondelle.de/" target="_blank" rel="noopener noreferrer"><img src="images/Logo-H-web.jpg" alt="" width="285" height="92" /></a></td>
<td style="background-color: #ebebeb; width: 40px;">
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</td>
</tr>
<tr class="acyeditor_delete">
<td style="background-color: #ebebeb; width: 40px;">&nbsp;</td>
<td class="acyeditor_text" style="background-color: #ffffff; border: 1px solid #dbdbdb; padding: 20px; width: 520px; margin: 15px auto;">
<h3 style="text-align: left;"><span style="color: #3491b7;">Hallo {subtag:name|part:first|ucfirst},</span></h3>
<p style="text-align: left;">"Hier den Text einsetzen"</p>
<p style="text-align: left;">&nbsp;</p>
<p style="text-align: left;">...mehr Infos rund ums''s Gleitschirmfliegen, zu unseren Kursen und Reisen findet ihr auf unserer Website&nbsp;<a href="http://www.fs-hirondelle.de/">www.fs-hirondelle.de</a>&nbsp;sowie in unserem&nbsp;<a href="https://www.youtube.com/channel/UCOwo0Wh2zoX_7nyArBdk_IQ">YouTube-Kanal</a>&nbsp;- schaut einfach mal rein!</p>
<p style="text-align: left;"><span style="color: #3491b7;"><em><strong>Luftige Grüße</strong></em></span><br /><span style="color: #3491b7;"><strong><em>Team Hirondelle</em></strong></span></p>
<p><span style="font-size: small;"><strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<br /></strong></span></p>
<p style="line-height: 100%; margin: 1px; text-align: center;"><span style="font-weight: bold;"><span style="font-size: xx-small;"><span style="font-weight: bold; font-family: Arial,''Arial Unicode MS'',Helvetica,sans-serif;">Flugschule Hirondelle</span><br /></span><span style="font-size: 14px; font-family: Arial, ''Arial Unicode MS'', Helvetica, sans-serif;"><span style="font-size: xx-small;">Untergasse 27 -&nbsp; 69469 Weinheim &nbsp;| &nbsp;Am Birnbach 6 - 76829 Landau<br /></span></span></span></p>
<p style="line-height: 100%; margin: 1px; text-align: center;">&nbsp;</p>
<address style="line-height: 100%; margin-top: 1px; margin-bottom: 1px;">
<p style="line-height: 100%; margin-top: 1px; margin-bottom: 10px; text-align: center;"><span style="font-weight: bold; font-size: 14px; font-family: Arial, ''Arial Unicode MS'', Helvetica, sans-serif;"><span style="font-size: xx-small;"><em>Telefon: </em></span></span><span style="font-weight: bold; font-size: 14px; font-family: Arial;"><em><span style="font-family: Arial, ''Arial Unicode MS'', Helvetica, sans-serif;"><span style="font-size: xx-small;">+49 (0) 6201 8452097</span></span></em></span></p>
</address>
<p style="margin: 4px 1px 1px; line-height: 100%; text-align: center;"><span style="color: #3491b7;"><span style="font-weight: bold;">Sparkasse SÜW<br />IBAN: DE32 5485 0010 1700 1976 41&nbsp; <br />BIC: SOLADES1SUW</span></span></p>
<p style="margin: 4px 1px 1px; line-height: 100%; text-align: center;"><span style="color: #3491b7;"><span style="font-weight: bold;"><br /></span><span style="font-weight: bold;"><a href="index.php?option=com_content&amp;view=article&amp;id=42:datenschutzerkl%C3%A4rung&amp;catid=2:allgemein">Datenschutzerklärung</a></span></span></p>
<p style="margin: 4px 1px 1px; line-height: 100%; text-align: center;"><span style="color: #3491b7;"><span style="font-weight: bold;"><br /></span><strong>Bitte tragen Sie uns in Ihr Adressbuch ein, <br />um einen einwandfreien Empfang zu ermöglichen</strong></span></p>
</td>
<td style="background-color: #ebebeb; width: 40px;">&nbsp;</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr style="line-height: 0px;">
<td style="background-color: #ebebeb; height: 40px;" valign="bottom"><img src="media/com_acymailing/templates/newsletter-4/bottom.png" alt="---" width="600" height="40" /></td>
</tr>
</tbody>
</table>
<div class="info acyeditor_delete acyeditor_text">Kein Interesse mehr am Newsletter? {unsubscribe}Abmelden{/unsubscribe}</div>
</div>', NULL, NULL, '2026-09-23 10:44:07', '2026-09-23 10:44:07'); -- old tempid 4
INSERT INTO NewsletterTemplate (id, name, body, design, thumbnailUrl, createdAt, updatedAt) VALUES ('4113c2f3-6426-465a-ba30-5450c68cd804', 'Newsletter Tandemflüge', '<div style="text-align: center; width: 100%; background-color: #ffffff;">
<div class="info acyeditor_delete acyeditor_text">{readonline}Dieser Newsletter enthält Grafiken, wenn du diese nicht angezeigt bekommst bitte mit einem Browser öffnen.{/readonline}</div>
<table style="text-align: justify; margin: auto; background-color: #ebebeb; border: 1px solid #e7e7e7; width: 600px;" cellspacing="0" cellpadding="0" align="center" bgcolor="#ebebeb">
<tbody class="acyeditor_sortable">
<tr style="line-height: 0px;">
<td style="background-color: #69b4c0; height: 38px;" valign="bottom"><img src="media/com_acymailing/templates/newsletter-4/top.png" alt=" - - - " /></td>
</tr>
<tr>
<td style="text-align: center; width: 600px;">
<table border="0" style="margin: auto; width: 600px;" cellspacing="0" cellpadding="0">
<tbody class="acyeditor_sortable">
<tr class="acyeditor_delete">
<td style="background-color: #ebebeb; width: 40px;">&nbsp;</td>
<td class="acyeditor_text" style="padding: 20px 0px; text-align: left; background-color: #ebebeb; width: 520px;"><img src="media/com_acymailing/templates/newsletter-4/message_icon.png" alt="-" style="margin: 0px 10px; float: left;" />
<h3><span style="color: #3491b7;">NEWSLETTER | TANDEMFLÜGE</span></h3>
</td>
</tr>
</tbody>
<tbody class="acyeditor_sortable">
<tr>
<td style="background-color: #ebebeb; width: 40px;">&nbsp;</td>
<td class="acyeditor_text" style="padding: 20px 0px; text-align: left; background-color: #fefefe; width: 520px;"><a href="http://www.flugschule-hirondelle.de/" target="_blank" rel="noopener noreferrer"><img src="images/Logo-H-web.jpg" alt="" /></a><a href="index.php/ct-menu-item-11" target="_blank" rel="noopener noreferrer"><img src="images/ebcbb8eb50.png" alt="" width="202" height="92" /></a></td>
<td style="background-color: #ebebeb; width: 40px;">
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</td>
</tr>
<tr class="acyeditor_delete">
<td style="background-color: #ebebeb; width: 40px;">&nbsp;</td>
<td class="acyeditor_text" style="background-color: #ffffff; border: 1px solid #dbdbdb; padding: 20px; width: 520px; margin: 15px auto; text-align: left;">
<h2><span style="color: #3491b7;">Hallo,</span></h2>
<p>"Hier den Text einsetzen"</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><span style="color: #3491b7;"><em><strong>Viele Grüße</strong></em></span><br /><span style="color: #3491b7;"><strong><em>Team Hirondelle</em></strong></span></p>
<p><strong><em><span style="font-size: small;"><strong>&nbsp;</strong></span></em></strong></p>
<p>&nbsp;<span style="font-size: small;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br /></strong></span></p>
<p style="text-align: center;">&nbsp;<span style="font-weight: bold;"><span style="font-size: xx-small;"><span style="font-weight: bold; font-family: Arial,''Arial Unicode MS'',Helvetica,sans-serif;">Flugschule Hirondelle</span> -&nbsp; </span><span style="font-size: 14px; font-family: Arial, ''Arial Unicode MS'', Helvetica, sans-serif;"><span style="font-size: xx-small;">Untergasse 27 -&nbsp; 69469 Weinheim -&nbsp; Germany</span></span></span></p>
<address style="line-height: 100%; margin-top: 1px; margin-bottom: 1px;">
<p style="line-height: 100%; margin-top: 1px; margin-bottom: 10px; text-align: center;"><span style="font-weight: bold; font-size: 14px; font-family: Arial;"><em><span style="font-family: Arial,''Arial Unicode MS'',Helvetica,sans-serif; font-size: xx-small;"><span style="font-weight: bold; font-size: 14px; font-family: Arial, ''Arial Unicode MS'', Helvetica, sans-serif;"><span style="font-size: xx-small;"><em>Telefon: </em></span></span><span style="font-weight: bold; font-size: 14px; font-family: Arial;"><em><span style="font-family: Arial, ''Arial Unicode MS'', Helvetica, sans-serif;"><span style="font-size: xx-small;">+49 (0) 6201 8452097</span></span></em></span></span></em></span></p>
</address>
<p style="text-align: center;"><span style="font-weight: bold; font-size: 14px; font-family: Arial;"><span style="font-size: xx-small;"><span style="color: #e2341d; font-family: Arial,''Arial Unicode MS'',Helvetica,sans-serif;"><span style="color: #3491b7;"><span style="font-weight: bold;">Sparkasse SÜW<br />IBAN: DE32 5485 0010 1700 1976 41&nbsp; <br />BIC: SOLADES1SUW</span></span><br /></span></span></span></p>
</td>
<td style="background-color: #ebebeb; width: 40px;">&nbsp;</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr style="line-height: 0px;">
<td style="background-color: #ebebeb; height: 40px;" valign="bottom"><img src="media/com_acymailing/templates/newsletter-4/bottom.png" alt="---" /></td>
</tr>
</tbody>
</table>
<div class="info acyeditor_delete acyeditor_text">Kein Interesse mehr am Newsletter? {unsubscribe}Unsubscribe{/unsubscribe}</div>
</div>', NULL, NULL, '2026-09-23 10:44:07', '2026-09-23 10:44:07'); -- old tempid 12
