import { Router } from 'express';
import { prisma } from '../utils/prisma';

const router = Router();

// Get the templates config by id (React Admin useGetOne)
router.get('/:id', async (req, res) => {
  try {
    const { id } = req.params;
    let config = await prisma.templatesConfig.findUnique({
      where: { id }
    });

    if (!config) {
      // Create default config if it doesn't exist
      const defaultEmails = {
        bookingConfirmation: {
          subject: 'Ihre Buchungsbestätigung für {EVENT_TITLE}',
          bodyHtml: '<p>Hallo {BOOKING_NAME},</p><p>vielen Dank für Ihre Buchung!</p><p>{EVENT_DETAILS}</p><p>{BOOKING_DETAILS}</p>',
          bodyText: 'Hallo {BOOKING_NAME},\n\nvielen Dank für Ihre Buchung!\n\n{EVENT_DETAILS}\n\n{BOOKING_DETAILS}'
        },
        adminCancellation: {
          subject: 'Stornierung Ihrer Buchung für {EVENT_TITLE}',
          bodyHtml: '<p>Hallo {BOOKING_NAME},</p><p>leider müssen wir Ihre Buchung stornieren.</p><p>{EVENT_DETAILS}</p>',
          bodyText: 'Hallo {BOOKING_NAME},\n\nleider müssen wir Ihre Buchung stornieren.\n\n{EVENT_DETAILS}'
        },
        userCancellation: {
          subject: 'Stornierungsbestätigung für {EVENT_TITLE}',
          bodyHtml: '<p>Hallo {BOOKING_NAME},</p><p>Ihre Stornierung wurde erfolgreich bearbeitet.</p><p>{EVENT_DETAILS}</p>',
          bodyText: 'Hallo {BOOKING_NAME},\n\nIhre Stornierung wurde erfolgreich bearbeitet.\n\n{EVENT_DETAILS}'
        }
      };

      config = await prisma.templatesConfig.create({
        data: {
          id,
          emails: defaultEmails,
          listViews: {
            signatureList: '##COM_MATUKIO_SIGNATURE_LIST##\n\n##COM_MATUKIO_NR##: MAT_EVENT_NUMBER\n##COM_MATUKIO_EVENT##: MAT_EVENT_TITLE\n##COM_MATUKIO_BEGIN##: MAT_EVENT_BEGIN\n##COM_MATUKIO_END##: MAT_EVENT_END\n##COM_MATUKIO_FEES##: MAT_EVENT_FEES\n\nMAT_NR MAT_BOOKING_NUMBER MAT_BOOKING_FIRSTNAME MAT_BOOKING_LASTNAME MAT_SIGN',
            participantList: '##COM_MATUKIO_PARTICIPANTS_LIST##\n\n##COM_MATUKIO_NR##: MAT_EVENT_NUMBER\n##COM_MATUKIO_FIELDS_TITLE##: MAT_EVENT_TITLE\n##COM_MATUKIO_BEGIN##: MAT_EVENT_BEGIN\n##COM_MATUKIO_END##: MAT_EVENT_END\n##COM_MATUKIO_FEES##: MAT_EVENT_FEES\n\n##COM_MATUKIO_NAME##: MAT_BOOKING_NAME\n##COM_MATUKIO_EMAIL##: MAT_BOOKING_EMAIL\n##COM_MATUKIO_BOOKING_NUMBER##: MAT_BOOKING_NUMBER\n##COM_MATUKIO_STATUS##: MAT_BOOKING_STATUS'
          },
          invoices: {
            pdfTemplate: '<table width="100%"><tr><td>Your Company<br>Your Company Address<br>Your Tax Number</td><td align="right">Your Logo</td></tr></table><br><br><table width="100%"><tr><td><b>Customer Information</b><br>MAT_BOOKING_NAME<br>MAT_BOOKING_STREET<br>MAT_BOOKING_ZIP MAT_BOOKING_CITY<br>MAT_BOOKING_COUNTRY</td><td><b>Invoice Information</b><br>Invoice Number: MAT_INVOICE_NUMBER<br>Invoice Date: MAT_INVOICE_DATE<br>Booking Number: MAT_BOOKING_NUMBER<br>Payment method: MAT_BOOKING_PAYMENT_METHOD</td></tr></table><br><br><table width="100%" border="1"><tr><th>#</th><th>Event</th><th>Net total</th></tr><tr><td>MAT_BOOKING_NRBOOKED</td><td>MAT_EVENT_TITLE</td><td>MAT_BOOKING_PAYMENT_NETTO</td></tr></table><br><div align="right">Net total: MAT_BOOKING_PAYMENT_NETTO<br>Tax total: MAT_BOOKING_PAYMENT_TAX<br><b>Total: MAT_BOOKING_PAYMENT_BRUTTO</b></div><br><br><b>Invoice Note</b><br>Your notes',
            emailSubject: 'Ihre Rechnung für {EVENT_TITLE} - {BOOKING_NUMBER}',
            emailBody: 'Hallo {BOOKING_NAME},\n\nanbei erhalten Sie Ihre Rechnung zur gebuchten Veranstaltung.\n\nMit freundlichen Grüßen\nIhre Flugschule Hirondelle'
          },
          certificates: {
            pdfTemplate: '##COM_MATUKIO_CERTIFICATE## for\n\nMAT_BOOKING_NAME\n\n##COM_MATUKIO_CERTIFICATE_ATTENDED##\n\nMAT_EVENT_TITLE\n\n##COM_MATUKIO_DATE##: MAT_DATE',
            emailSubject: '##COM_MATUKIO_EMAIL_SUBJECT_CERTIFICATE## MAT_EVENT_TITLE',
            emailBody: '##COM_MATUKIO_EMAIL_GREETING## MAT_BOOKING_NAME,\n\n##COM_MATUKIO_YOU_HAVE_BEEN_CERTIFICATED##\n\n##COM_MATUKIO_YOU_HAVE_BEEN_CERTIFICATED## MAT_EVENT_ALL_DETAILS_HTML MAT_SIGNATURE'
          },
          tickets: {
            ticketTemplate: 'MAT_EVENT_TITLE - MAT_EVENT_BEGIN\nMAT_BOOKING_NRBOOKED\nMAT_BOOKING_NUMBER\nMAT_BOOKING_CHECKIN_QRCODE\nMAT_BOOKING_PAYMENT_BRUTTO',
            nametagTemplate: 'MAT_BOOKING_FIRSTNAME MAT_BOOKING_LASTNAME\nMAT_BOOKING_COUNTRY\n\nMAT_EVENT_TITLE MAT_BOOKING_ID',
            backgroundImage: 'images/powered_by.png'
          },
          csvXml: {
            csvTemplate: "'MAT_BOOKING_NUMBER';'MAT_EVENT_TITLE';'MAT_CSV_BOOKING_DETAILS';'MAT_BOOKING_PAYMENT_BRUTTO';'MAT_BOOKING_NAME';'MAT_BOOKING_PAYMENT_METHOD';'MAT_BOOKING_STATUS';'MAT_BOOKING_EXTRA_PAYMENT_OPTIONS';'MAT_BOOKING_PAYMENT_STATUS'",
            xmlTemplate: '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<!-- Generated by Matukio -->\n<BOOKING>\n<BOOKING_NUMBER>MAT_BOOKING_NUMBER</BOOKING_NUMBER>\n<EVENT>MAT_EVENT_TITLE</EVENT>\n<EVENT_NUMBER>MAT_EVENT_NUMBER</EVENT_NUMBER>\n<TITLE>MAT_BOOKING_TITLE</TITLE>\n<FIRSTNAME>MAT_BOOKING_FIRSTNAME</FIRSTNAME>\n<LASTNAME>MAT_BOOKING_LASTNAME</LASTNAME>\n<COMPANY>MAT_BOOKING_COMPANY</COMPANY>\n<STREET>MAT_BOOKING_STREET</STREET>\n<ZIPCODE>MAT_BOOKING_ZIP</ZIPCODE>\n<CITY>MAT_BOOKING_CITY</CITY>\n<COUNTRY>MAT_BOOKING_COUNTRY</COUNTRY>\n<PHONE>MAT_BOOKING_PHONE</PHONE>\n<MOBILE>MAT_BOOKING_MOBILE</MOBILE>\n<EMAIL>MAT_BOOKING_EMAIL</EMAIL>\n<COMMENT>MAT_BOOKING_COMMENT</COMMENT>\n<PLACES>MAT_BOOKING_BOOKEDNR</PLACES>\n<AMOUNT>MAT_BOOKING_GROSS</AMOUNT>\n<PERSONS>\nMAT_XML_BOOKING_OTHER_PERSON_DATA\n</PERSONS>\n</BOOKING>'
          }
        }
      });
    }

    res.json(config);
  } catch (error) {
    console.error('Error fetching templates config:', error);
    res.status(500).json({ error: 'Failed to fetch templates config' });
  }
});

// Update the templates config
router.put('/:id', async (req, res) => {
  try {
    const { id } = req.params;
    
    // Extract only valid fields
    const { emails, listViews, invoices, certificates, tickets, csvXml } = req.body;
    
    // Only update if at least one valid field is provided
    const updateData: any = {};
    if (emails !== undefined) updateData.emails = emails;
    if (listViews !== undefined) updateData.listViews = listViews;
    if (invoices !== undefined) updateData.invoices = invoices;
    if (certificates !== undefined) updateData.certificates = certificates;
    if (tickets !== undefined) updateData.tickets = tickets;
    if (csvXml !== undefined) updateData.csvXml = csvXml;

    const config = await prisma.templatesConfig.upsert({
      where: { id },
      update: updateData,
      create: {
        id,
        emails: emails || {},
        listViews: listViews || {},
        invoices: invoices || {},
        certificates: certificates || {},
        tickets: tickets || {},
        csvXml: csvXml || {}
      }
    });

    res.json(config);
  } catch (error) {
    console.error('Error updating templates config:', error);
    res.status(500).json({ error: 'Failed to update templates config' });
  }
});

export default router;
